-- Fase 19 (#104): atribuicao de icones a temas e desafios, feita direto
-- no banco dev durante a fase de teste - precisa ser repetida em
-- producao (nao veio via migration/codigo, e' dado). Gerado a partir
-- do estado real do banco dev, casando por nome/pergunta (estavel
-- entre ambientes, ao contrario do id autoincrement).

-- Temas
UPDATE temas SET icone='tecnologia' WHERE nome='Otimização e Celeridade da Prestação Jurisdicional (Tema 1)';
UPDATE temas SET icone='atendimento' WHERE nome='Aprimoramento do Atendimento ao Cidadão e Acesso à Justiça (Tema 2)';
UPDATE temas SET icone='gestao' WHERE nome='Eficiência e Sustentabilidade da Gestão Administrativa (Tema 3)';
UPDATE temas SET icone='gestao' WHERE nome='Processos internos (Tema 1)';
UPDATE temas SET icone='juridico' WHERE nome='Atividade finalística (Tema 2)';
UPDATE temas SET icone='acessibilidade' WHERE nome='Cidadania e Justiça Inclusiva (Tema 3)';

-- Desafios (casados por tema.nome + desafio.pergunta, ja que a mesma
-- pergunta se repete em mais de um tema/trilha)
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='viagem' WHERE t.nome='Processos internos (Tema 1)' AND d.pergunta='Como podemos viabilizar o gerenciamento e aquisição de passagens aéreas por meio de credenciamento permanente de agências de viagens e companhias aéreas, para centralizar demandas e automatizar a busca, triagem e comparação de passagens em tempo real, garantindo a seleção pelo menor preço, celeridade na emissão e total rastreabilidade para o TJRR?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='pessoas' WHERE t.nome='Processos internos (Tema 1)' AND d.pergunta='Como podemos otimizar e automatizar o processo de análise, conferência e validação dos requerimentos de conversão de férias no Setor de Monitoramento de Desempenho, eliminando o gargalo do processamento manual massivo de cerca de 800 pedidos dentro da janela crítica de apenas 4 dias?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='dados' WHERE t.nome='Processos internos (Tema 1)' AND d.pergunta='Como podemos construir uma estratégia que propicie a elaboração, o fomento e o monitoramento contínuo de um banco de dados unificado para taxas de absenteísmo na SGP/SUBGEP, facilitando a integração de informações e o suporte preventivo à qualidade de vida dos servidores do TJRR?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='sustentabilidade' WHERE t.nome='Processos internos (Tema 1)' AND d.pergunta='Como podemos melhorar o monitoramento e a coleta unificada de dados de sustentabilidade no SSRS, de modo a mitigar o retrabalho no preenchimento de relatórios obrigatórios (PLS, Resolução CNJ nº 400/2021 e Inventário GEE) e viabilizar a rastreabilidade das ações de compensação ambiental no TJRR de maneira automatizada e padronizada?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='gestao' WHERE t.nome='Processos internos (Tema 1)' AND d.pergunta='Como podemos automatizar e integrar todo o ciclo de gestão das demandas da Subsecretaria de Sistemas (SubSi), desde o recebimento por diferentes canais (E-mail, SEI e Aranda) até a triagem, registro, implementação, acompanhamento, documentação e geração de informações gerenciais, eliminando atividades manuais repetitivas, aumentando a rastreabilidade e proporcionando inteligência estratégica para a tomada de decisão?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='seguranca' WHERE t.nome='Processos internos (Tema 1)' AND d.pergunta='Como podemos aumentar o engajamento dos servidores nas ações de conscientização sobre segurança da informação, tornando essas iniciativas mais atrativas, efetivas e capazes de fortalecer a cultura de segurança no Tribunal de Justiça de Roraima?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='patrimonio' WHERE t.nome='Processos internos (Tema 1)' AND d.pergunta='Como podemos modernizar e integrar a gestão dos ativos patrimoniais e de Tecnologia da Informação do TJRR, garantindo rastreabilidade, atualização contínua das movimentações e confiabilidade do inventário institucional, reduzindo processos manuais e retrabalho entre as unidades responsáveis?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='infraestrutura' WHERE t.nome='Processos internos (Tema 1)' AND d.pergunta='Como podemos, de forma automatizada e centralizada, mensurar e atribuir os custos de consumo de recursos (VMs, Clusters K8s, Deployments, Pods e Containers) para permitir uma gestão financeira transparente e eficiente da infraestrutura de TI do TJRR?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='transparencia' WHERE t.nome='Processos internos (Tema 1)' AND d.pergunta='Como podemos propiciar a extração automatizada, integrada e centralizada de relatórios de dados funcionais e remuneratórios na Secretaria de Gestão de Pessoas, eliminando o uso de controles paralelos e otimizando o envio de informações obrigatórias ao Portal da Transparência do TJRR?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='pessoas' WHERE t.nome='Processos internos (Tema 1)' AND d.pergunta='Como podemos dimensionar e alocar, de forma eficiente, a força de trabalho nas unidades de apoio direto e indireto do TJRR, desenvolvendo uma metodologia institucional integrada a uma ferramenta tecnológica que facilite a distribuição equilibrada de pessoal, cargos e funções, mitigando assimetrias e a sobrecarga de trabalho?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='seguranca' WHERE t.nome='Processos internos (Tema 1)' AND d.pergunta='Como podemos gerir, de forma preventiva, integrada e sistematizada de informações de risco, os deslocamentos e missões institucionais no GABMIL, unindo inteligência e análise territorial para mitigar a exposição de magistrados e servidores no Estado de Roraima?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='automacao' WHERE t.nome='Atividade finalística (Tema 2)' AND d.pergunta='Como podemos realizar a correição judicial do acervo processual das unidades judiciárias no sistema Projudi, superando as limitações da análise manual por amostragem e padronizando a detecção de movimentações inadequadas ou redundantes?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='juridico' WHERE t.nome='Atividade finalística (Tema 2)' AND d.pergunta='Como podemos estimular a resolução de conflitos por meios alternativos e reduzir o volume de novas petições, aliviando a carga de trabalho das secretarias e gabinetes para garantir uma resposta mais célere e efetiva ao cidadão?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='automacao' WHERE t.nome='Atividade finalística (Tema 2)' AND d.pergunta='Como podemos construir uma estratégia de automação para a execução de tarefas repetitivas e de baixa complexidade no sistema Projudi, visando dar fluidez ao alto volume de movimentações processuais, reduzir o tempo de tramitação e garantir melhor qualidade de vida e saúde mental para um quadro reduzido de servidores?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='comunicacao' WHERE t.nome='Atividade finalística (Tema 2)' AND d.pergunta='Como podemos melhorar a transcrição automatizada e prover tradução em tempo real de audiências judiciais multilíngues, visando ampliar o acesso à justiça, reduzir a morosidade processual e eliminar a dependência de serviços externos especializados?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='viagem' WHERE t.nome='Cidadania e Justiça Inclusiva (Tema 3)' AND d.pergunta='Como podemos facilitar o processamento dos pedidos de autorização de viagem para menores, feito pelos pais e responsáveis, para que seja menos custoso a eles e ao judiciário?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='acessibilidade' WHERE t.nome='Cidadania e Justiça Inclusiva (Tema 3)' AND d.pergunta='Como podemos facilitar o acesso aos serviços de Justiça e cidadania para as comunidades do Baixo Rio Branco (atendidas pelas comarcas de Caracaraí e Rorainópolis), reduzindo os custos de deslocamento fluvial e simplificando a jornada do usuário por meio de ferramentas digitais acessíveis?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='automacao' WHERE t.nome='Otimização e Celeridade da Prestação Jurisdicional (Tema 1)' AND d.pergunta='Como podemos realizar a correição judicial do acervo processual das unidades judiciárias no sistema Projudi, superando as limitações da análise manual por amostragem e padronizando a detecção de movimentações inadequadas ou redundantes?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='juridico' WHERE t.nome='Otimização e Celeridade da Prestação Jurisdicional (Tema 1)' AND d.pergunta='Como podemos estimular a resolução de conflitos por meios alternativos e reduzir o volume de novas petições, aliviando a carga de trabalho das secretarias e gabinetes para garantir uma resposta mais célere e efetiva ao cidadão?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='automacao' WHERE t.nome='Otimização e Celeridade da Prestação Jurisdicional (Tema 1)' AND d.pergunta='Como podemos automatizar a execução de tarefas repetitivas e de baixa complexidade no sistema Projudi, visando dar fluidez ao alto volume de movimentações processuais, reduzir o tempo de tramitação e garantir melhor qualidade de vida e saúde mental para um quadro reduzido de servidores?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='comunicacao' WHERE t.nome='Otimização e Celeridade da Prestação Jurisdicional (Tema 1)' AND d.pergunta='Como podemos melhorar a transcrição automatizada e inserir tradução em tempo real de audiências judiciais multilíngues, visando ampliar o acesso à justiça, reduzir a morosidade processual e eliminar a dependência de serviços externos especializados?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='viagem' WHERE t.nome='Aprimoramento do Atendimento ao Cidadão e Acesso à Justiça (Tema 2)' AND d.pergunta='Como podemos facilitar o processamento dos pedidos de autorização de viagem para menores, feito pelos pais e responsáveis, para que seja menos custoso a eles e ao judiciário?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='acessibilidade' WHERE t.nome='Aprimoramento do Atendimento ao Cidadão e Acesso à Justiça (Tema 2)' AND d.pergunta='Como podemos facilitar o acesso aos serviços de Justiça e cidadania para as comunidades do Baixo Rio Branco (atendidas pelas comarcas de Caracaraí e Rorainópolis), reduzindo os custos de deslocamento fluvial e simplificando a jornada do usuário por meio de ferramentas digitais acessíveis?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='viagem' WHERE t.nome='Eficiência e Sustentabilidade da Gestão Administrativa (Tema 3)' AND d.pergunta='Como podemos viabilizar o gerenciamento e aquisição de passagens aéreas por meio de credenciamento permanente de agências de viagens e companhias aéreas, para centralizar demandas e automatizar a busca, triagem e comparação de passagens em tempo real, garantindo a seleção pelo menor preço, celeridade na emissão e total rastreabilidade para o TJRR?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='dados' WHERE t.nome='Eficiência e Sustentabilidade da Gestão Administrativa (Tema 3)' AND d.pergunta='Como podemos propiciar a elaboração, o fomento e o monitoramento contínuo de um banco de dados unificado para taxas de absenteísmo na SGP/SUBGEP, facilitando a integração de informações e o suporte preventivo à qualidade de vida dos servidores do TJRR?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='sustentabilidade' WHERE t.nome='Eficiência e Sustentabilidade da Gestão Administrativa (Tema 3)' AND d.pergunta='Como podemos melhorar o monitoramento e a coleta unificada de dados de sustentabilidade no SSRS, de modo a mitigar o retrabalho no preenchimento de relatórios obrigatórios (PLS, Resolução CNJ nº 400/2021 e Inventário GEE) e viabilizar a rastreabilidade das ações de compensação ambiental no TJRR de maneira automatizada e padronizada?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='gestao' WHERE t.nome='Eficiência e Sustentabilidade da Gestão Administrativa (Tema 3)' AND d.pergunta='Como podemos automatizar e integrar todo o ciclo de gestão das demandas da Subsecretaria de Sistemas (SubSi), desde o recebimento por diferentes canais (E-mail, SEI e Aranda) até a triagem, registro, implementação, acompanhamento, documentação e geração de informações gerenciais, eliminando atividades manuais repetitivas, aumentando a rastreabilidade e proporcionando inteligência estratégica para a tomada de decisão?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='patrimonio' WHERE t.nome='Eficiência e Sustentabilidade da Gestão Administrativa (Tema 3)' AND d.pergunta='Como podemos modernizar e integrar a gestão dos ativos patrimoniais e de Tecnologia da Informação do TJRR, garantindo rastreabilidade, atualização contínua das movimentações e confiabilidade do inventário institucional, reduzindo processos manuais e retrabalho entre as unidades responsáveis?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='infraestrutura' WHERE t.nome='Eficiência e Sustentabilidade da Gestão Administrativa (Tema 3)' AND d.pergunta='Como podemos, de forma automatizada e centralizada, mensurar e atribuir os custos de consumo de recursos (VMs, Clusters K8s, Deployments, Pods e Containers) para permitir uma gestão financeira transparente e eficiente da infraestrutura de TI do TJRR?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='transparencia' WHERE t.nome='Eficiência e Sustentabilidade da Gestão Administrativa (Tema 3)' AND d.pergunta='Como podemos propiciar a extração automatizada, integrada e centralizada de relatórios de dados funcionais e remuneratórios na Secretaria de Gestão de Pessoas, eliminando o uso de controles paralelos e otimizando o envio de informações obrigatórias ao Portal da Transparência do TJRR?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='pessoas' WHERE t.nome='Eficiência e Sustentabilidade da Gestão Administrativa (Tema 3)' AND d.pergunta='Como podemos dimensionar e alocar, de forma eficiente, a força de trabalho nas unidades de apoio direto e indireto do TJRR, desenvolvendo uma metodologia institucional integrada a uma ferramenta tecnológica que facilite a distribuição equilibrada de pessoal, cargos e funções, mitigando assimetrias e a sobrecarga de trabalho?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='seguranca' WHERE t.nome='Eficiência e Sustentabilidade da Gestão Administrativa (Tema 3)' AND d.pergunta='Como podemos gerir, de forma preventiva, integrada e sistematizada de informações de risco, os deslocamentos e missões institucionais no GABMIL, unindo inteligência e análise territorial para mitigar a exposição de magistrados e servidores no Estado de Roraima?';
UPDATE desafios d JOIN temas t ON t.id = d.tema_id SET d.icone='dados' WHERE t.nome='Eficiência e Sustentabilidade da Gestão Administrativa (Tema 3)' AND d.pergunta='Como podemos automatizar o acompanhamento do portfólio de projetos, ações, programas e desafios do NPI/TJRR, de modo que o registro de progresso de cada etapa seja feito uma única vez e alimente automaticamente o painel de Business Intelligence, reduzindo o esforço de atualização manual e assegurando que os dados apresentados à gestão reflitam o estado real e atualizado de cada iniciativa?';
